spring:
  datasource:
    url: jdbc:h2:file:./data/mdb-task-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    dispatch-options-request: true
  h2:
    console:
      enabled: true

api:
  auth:
    username: admin
    password: $2a$10$2cC3rWJ49PrjbnzRfN.6.uCDept9HNm8R.lFD9nLrRAYdLafRec8u

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
server:
  servlet:
    context-path: /api
logging:
  level:
      org.springframework.security: info

springdoc:
  api-docs:
    path: /documentation
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
